version: "3.9"

services:
  backend:
    build: ./backend-go
    ports:
      - "8080:8080"
    depends_on:
      - ai
      - db
    environment:
      - AI_SERVICE_URL=http://ai:8000
      - DB_URL=postgres://vector:vectorpass@db:5432/vector_insight
      - PORT=8080

  ai:
    build: ./ai-python
    ports:
      - "8000:8000"

  db:
    image: postgis/postgis:15-3.3
    container_name: vector_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: vector
      POSTGRES_PASSWORD: vectorpass
      POSTGRES_DB: vector_insight
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
