version: "3.9"
services:
  db:
    image: postgis/postgis:15-3.3
    container_name: vector_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: vector
      POSTGRES_PASSWORD: vectorpass
      POSTGRES_DB: vector_insight
    volumes:
      - ./postgres_data:/var/lib/postgresql/data